# Generated by Django 3.2.6 on 2021-08-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBD', '0002_auto_20210810_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='obd',
            name='Rpm',
            field=models.CharField(default='', max_length=70),
        ),
    ]
