# Generated by Django 3.2.6 on 2021-08-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20210810_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='Device_Status',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='East_West',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='IMEI',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='Internal_Battery_Level',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='North_South',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='OBD_TAG_ID',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='OrgID',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='Signal_Strength',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='SiteID',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='VOB_ID',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='timeout',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
